app <- ShinyDriver$new("../../", seed = 1234, loadTimeout = 60000)
app$snapshotInit("mytest", screenshot = FALSE)

app$setInputs(userInputId2 = c("I", "II"), timeout_ = 30000)
app$snapshot()
app$setInputs(param_region = "Stockholm-Gotland", timeout_ = 30000)
app$snapshot()
app$setInputs(param_levelpresent = "Sjukhus", timeout_ = 30000)
app$snapshot()
app$setInputs(param_ownhospital = "Sjukhus 10-1-a", timeout_ = 30000)
app$snapshot()
app$setInputs(param_period_year = c(2013, 2016), timeout_ = 30000)
app$snapshot()
app$setInputs(param_periodSplit = TRUE, timeout_ = 30000)
app$snapshot()
app$setInputs(userInputId1 = c(18, 70), timeout_ = 30000)
app$snapshot()
